#include "emojis.h"

#include "utils.h"

namespace gsmq {

#define _LETTER(__name) \
	{ gsmq::__##__name, #__name }
const std::unordered_map<char32_t, std::string> __letter_names = {
	_LETTER(green_apple),
	_LETTER(apple),
	_LETTER(pear),
	_LETTER(tangerine),
	_LETTER(lemon),
	_LETTER(banana),
	_LETTER(watermelon),
	_LETTER(grapes),
	_LETTER(blueberries),
	_LETTER(strawberry),
	_LETTER(melon),
	_LETTER(cherries),
	_LETTER(peach),
	_LETTER(mango),
	_LETTER(pineapple),
	_LETTER(coconut),
	_LETTER(kiwi),
	_LETTER(tomato),
	_LETTER(eggplant),
	_LETTER(avocado),
	_LETTER(olive),
	_LETTER(broccoli),
	_LETTER(leafy_green),
	_LETTER(bell_pepper),
	_LETTER(cucumber),
	_LETTER(hot_pepper),
	_LETTER(corn),
	_LETTER(carrot),
	_LETTER(garlic),
	_LETTER(onion),
	_LETTER(potato),
	_LETTER(sweet_potato),
	_LETTER(croissant),
	_LETTER(bagel),
	_LETTER(bread),
	_LETTER(french_bread),
	_LETTER(flatbread),
	_LETTER(pretzel),
	_LETTER(cheese),
	_LETTER(egg),
	_LETTER(cooking),
	_LETTER(butter),
	_LETTER(pancakes),
	_LETTER(waffle),
	_LETTER(bacon),
	_LETTER(cut_of_meat),
	_LETTER(poultry_leg),
	_LETTER(meat_on_bone),
	_LETTER(hotdog),
	_LETTER(hamburger),
	_LETTER(fries),
	_LETTER(pizza),
	_LETTER(sandwich),
	_LETTER(stuffed_flatbread),
	_LETTER(falafel),
	_LETTER(taco),
	_LETTER(burrito),
	_LETTER(tamale),
	_LETTER(salad),
	_LETTER(shallow_pan_of_food),
	_LETTER(fondue),
	_LETTER(canned_food),
	_LETTER(spaghetti),
	_LETTER(ramen),
	_LETTER(stew),
	_LETTER(curry),
	_LETTER(sushi),
	_LETTER(bento),
	_LETTER(dumpling),
	_LETTER(oyster),
	_LETTER(fried_shrimp),
	_LETTER(rice_ball),
	_LETTER(rice),
	_LETTER(rice_cracker),
	_LETTER(fish_cake),
	_LETTER(fortune_cookie),
	_LETTER(moon_cake),
	_LETTER(oden),
	_LETTER(dango),
	_LETTER(shaved_ice),
	_LETTER(ice_cream),
	_LETTER(icecream),
	_LETTER(pie),
	_LETTER(cupcake),
	_LETTER(cake),
	_LETTER(birthday),
	_LETTER(custard),
	_LETTER(lollipop),
	_LETTER(candy),
	_LETTER(chocolate_bar),
	_LETTER(popcorn),
	_LETTER(doughnut),
	_LETTER(cookie),
	_LETTER(chestnut),
	_LETTER(peanuts),
	_LETTER(honey_pot),
	_LETTER(milk),
	_LETTER(baby_bottle),
	_LETTER(coffee),
	_LETTER(tea),
	_LETTER(teapot),
	_LETTER(mate),
	_LETTER(bubble_tea),
	_LETTER(beverage_box),
	_LETTER(cup_with_straw),
	_LETTER(sake),
	_LETTER(beer),
	_LETTER(beers),
	_LETTER(champagne_glass),
	_LETTER(wine_glass),
	_LETTER(tumbler_glass),
	_LETTER(cocktail),
	_LETTER(tropical_drink),
	_LETTER(champagne),
	_LETTER(ice_cube),
	_LETTER(spoon),
	_LETTER(fork_and_knife),
	_LETTER(fork_knife_plate),
	_LETTER(bowl_with_spoon),
	_LETTER(takeout_box),
	_LETTER(chopsticks),
	_LETTER(salt),
};

#undef _LETTER
#define _LETTER(__str, __name) \
	{ __str, gsmq::__name }
const std::map<std::string, char32_t> __sgtf = {
	_LETTER("gA", __green_apple),
	_LETTER("A", __apple),
	_LETTER("P", __pear),
	_LETTER("TT", __tangerine),
	_LETTER("L", __lemon),
	_LETTER("B", __banana),
	_LETTER("wM", __watermelon),
	_LETTER("G", __grapes),
	_LETTER("bB", __blueberries),
	_LETTER("sB", __strawberry),
	_LETTER("M", __melon),
	_LETTER("CH", __cherries),
	_LETTER("PC", __peach),
	_LETTER("MG", __mango),
	_LETTER("pA", __pineapple),
	_LETTER("cN", __coconut),
	_LETTER("K", __kiwi),
	_LETTER("T", __tomato),
	_LETTER("eP", __eggplant),
	_LETTER("AV", __avocado),
	_LETTER("O", __olive),
	_LETTER("BC", __broccoli),
	_LETTER("LT", __leafy_green),
	_LETTER("bPP", __bell_pepper),
	_LETTER("CC", __cucumber),
	_LETTER("hPP", __hot_pepper),
	_LETTER("CN", __corn),
	_LETTER("C", __carrot),
	_LETTER("GA", __garlic),
	_LETTER("ZERO", __onion),
	_LETTER("PT", __potato),
	_LETTER("sPT", __sweet_potato),
	_LETTER("cBR", __croissant),
	_LETTER("bBR", __bagel),
	_LETTER("BR", __bread),
	_LETTER("fBR", __french_bread),
	_LETTER("flBR", __flatbread),
	_LETTER("pBR", __pretzel),
	_LETTER("Q", __cheese),
	_LETTER("EG", __egg),
	_LETTER("?", __cooking),
	_LETTER("BU", __butter),
	_LETTER("pCK", __pancakes),
	_LETTER("W", __waffle),
	_LETTER("bM", __bacon),
	_LETTER("cM", __cut_of_meat),
	_LETTER("pM", __poultry_leg),
	_LETTER("mM", __meat_on_bone),
	_LETTER("HD", __hotdog),
	_LETTER("hFF", __hamburger),
	_LETTER("fFF", __fries),
	_LETTER("pFF", __pizza),
	_LETTER("sFF", __sandwich),
	_LETTER("¿", __stuffed_flatbread),
	_LETTER("FLF", __falafel),
	_LETTER("TK", __taco),
	_LETTER("BUR", __burrito),
	_LETTER("TM", __tamale),
	_LETTER("SL", __salad),
	_LETTER("QQ", __shallow_pan_of_food),
	_LETTER("FD", __fondue),
	_LETTER("CF", __canned_food),
	_LETTER("S", __spaghetti),
	_LETTER("RA", __ramen),
	_LETTER("SW", __stew),
	_LETTER("CR", __curry),
	_LETTER("suF", __sushi),
	_LETTER("BN", __bento),
	_LETTER("D", __dumpling),
	_LETTER("Y", __oyster),
	_LETTER("fsF", __fried_shrimp),
	_LETTER("bR", __rice_ball),
	_LETTER("R", __rice),
	_LETTER("cR", __rice_cracker),
	_LETTER("FCK", __fish_cake),
	_LETTER("NICE", __fortune_cookie),
	_LETTER("mCK", __moon_cake),
	_LETTER("oSP", __oden),
	_LETTER("dSP", __dango),
	_LETTER("sSP", __shaved_ice),
	_LETTER("I", __ice_cream),
	_LETTER("icSP", __icecream),
	_LETTER("pSP", __pie),
	_LETTER("cCK", __cupcake),
	_LETTER("CK", __cake),
	_LETTER("bdCK", __birthday),
	_LETTER("cuCK", __custard),
	_LETTER("LL", __lollipop),
	_LETTER("SP", __candy),
	_LETTER("cbSP", __chocolate_bar),
	_LETTER("pNHCL", __popcorn),
	_LETTER("πRIIIIπR", __doughnut),
	_LETTER("BSC", __cookie),
	_LETTER("chN", __chestnut),
	_LETTER("pN", __peanuts),
	_LETTER("CP", __honey_pot),
	_LETTER("MLK", __milk),
	_LETTER("bMLK", __baby_bottle),
	_LETTER("HERESY", __coffee),
	_LETTER("YAY", __tea),
	_LETTER("HARBOUR", __tea),
	_LETTER("pYAY", __teapot),
	_LETTER("pHARBOUR", __teapot),
	_LETTER("mYAY", __mate),
	_LETTER("mHARBOUR", __mate),
	_LETTER("bYAY", __bubble_tea),
	_LETTER("bHARBOUR", __bubble_tea),
	_LETTER("?¿", __beverage_box),
	_LETTER("¿?", __cup_with_straw),
	_LETTER("sCIIHVOH", __sake),
	_LETTER("bCIIHVOH", __beer),
	_LETTER("bbCIIHVOH", __beers),
	_LETTER("cgCIIHVOH", __champagne_glass),
	_LETTER("wCIIHVOH", __wine_glass),
	_LETTER("tCIIHVOH", __tumbler_glass),
	_LETTER("ckCIIHVOH", __cocktail),
	_LETTER("trCIIHVOH", __tropical_drink),
	_LETTER("cCIIHVOH", __champagne),
	_LETTER("COLD", __ice_cube),
	_LETTER("sNOT_FOOD", __spoon),
	_LETTER("fkNOT_FOOD", __fork_and_knife),
	_LETTER("fkpNOT_FOOD", __fork_knife_plate),
	_LETTER("bsNOT_FOOD", __bowl_with_spoon),
	_LETTER("tbNOT_FOOD", __takeout_box),
	_LETTER("CHOP", __chopsticks),
	_LETTER("NHCL", __salt),
};

} // namespace gsmq