#include "emojis.h"
#include "utils.h"
#include <utility>


#define EMOJI(name) \
	{ CAT(L, STR(name)), static_cast<wchar_t>(Gumsmaq::name) }
const std::unordered_map<std::wstring, wchar_t> name_gumsmaq_table = {
	EMOJI(green_apple),
	EMOJI(apple),
	EMOJI(pear),
	EMOJI(tangerine),
	EMOJI(lemon),
	EMOJI(banana),
	EMOJI(watermelon),
	EMOJI(grapes),
	EMOJI(blueberries),
	EMOJI(strawberry),
	EMOJI(melon),
	EMOJI(cherries),
	EMOJI(peach),
	EMOJI(mango),
	EMOJI(pineapple),
	EMOJI(coconut),
	EMOJI(kiwi),
	EMOJI(tomato),
	EMOJI(eggplant),
	EMOJI(avocado),
	EMOJI(olive),
	EMOJI(broccoli),
	EMOJI(leafy_green),
	EMOJI(bell_pepper),
	EMOJI(cucumber),
	EMOJI(hot_pepper),
	EMOJI(corn),
	EMOJI(carrot),
	EMOJI(garlic),
	EMOJI(onion),
	EMOJI(potato),
	EMOJI(sweet_potato),
	EMOJI(croissant),
	EMOJI(bagel),
	EMOJI(bread),
	EMOJI(french_bread),
	EMOJI(flatbread),
	EMOJI(pretzel),
	EMOJI(cheese),
	EMOJI(egg),
	EMOJI(cooking),
	EMOJI(butter),
	EMOJI(pancakes),
	EMOJI(waffle),
	EMOJI(bacon),
	EMOJI(cut_of_meat),
	EMOJI(poultry_leg),
	EMOJI(meat_on_bone),
	EMOJI(hotdog),
	EMOJI(hamburger),
	EMOJI(fries),
	EMOJI(pizza),
	EMOJI(sandwich),
	EMOJI(stuffed_flatbread),
	EMOJI(falafel),
	EMOJI(taco),
	EMOJI(burrito),
	EMOJI(tamale),
	EMOJI(salad),
	EMOJI(shallow_pan_of_food),
	EMOJI(fondue),
	EMOJI(canned_food),
	EMOJI(spaghetti),
	EMOJI(ramen),
	EMOJI(stew),
	EMOJI(curry),
	EMOJI(sushi),
	EMOJI(bento),
	EMOJI(dumpling),
	EMOJI(oyster),
	EMOJI(fried_shrimp),
	EMOJI(rice_ball),
	EMOJI(rice),
	EMOJI(rice_cracker),
	EMOJI(fish_cake),
	EMOJI(fortune_cookie),
	EMOJI(moon_cake),
	EMOJI(oden),
	EMOJI(dango),
	EMOJI(shaved_ice),
	EMOJI(ice_cream),
	EMOJI(icecream),
	EMOJI(pie),
	EMOJI(cupcake),
	EMOJI(cake),
	EMOJI(birthday),
	EMOJI(custard),
	EMOJI(lollipop),
	EMOJI(candy),
	EMOJI(chocolate_bar),
	EMOJI(popcorn),
	EMOJI(doughnut),
	EMOJI(cookie),
	EMOJI(chestnut),
	EMOJI(peanuts),
	EMOJI(honey_pot),
	EMOJI(milk),
	EMOJI(baby_bottle),
	EMOJI(coffee),
	EMOJI(tea),
	EMOJI(teapot),
	EMOJI(mate),
	EMOJI(bubble_tea),
	EMOJI(beverage_box),
	EMOJI(cup_with_straw),
	EMOJI(sake),
	EMOJI(beer),
	EMOJI(beers),
	EMOJI(champagne_glass),
	EMOJI(wine_glass),
	EMOJI(tumbler_glass),
	EMOJI(cocktail),
	EMOJI(tropical_drink),
	EMOJI(champagne),
	EMOJI(ice_cube),
	EMOJI(spoon),
	EMOJI(fork_and_knife),
	EMOJI(fork_knife_plate),
	EMOJI(bowl_with_spoon),
	EMOJI(takeout_box),
	EMOJI(chopsticks),
	EMOJI(salt),
};

#undef EMOJI
const std::unordered_map<std::wstring, wchar_t> abbr_gumsmaq_table = {
	{L"gA", static_cast<wchar_t>(Gumsmaq::green_apple)},
	{L"A", static_cast<wchar_t>(Gumsmaq::apple)},
	{L"P", static_cast<wchar_t>(Gumsmaq::pear)},
	{L"TT", static_cast<wchar_t>(Gumsmaq::tangerine)},
	{L"L", static_cast<wchar_t>(Gumsmaq::lemon)},
	{L"B", static_cast<wchar_t>(Gumsmaq::banana)},
	{L"wM", static_cast<wchar_t>(Gumsmaq::watermelon)},
	{L"G", static_cast<wchar_t>(Gumsmaq::grapes)},
	{L"bB", static_cast<wchar_t>(Gumsmaq::blueberries)},
	{L"sB", static_cast<wchar_t>(Gumsmaq::strawberry)},
	{L"M", static_cast<wchar_t>(Gumsmaq::melon)},
	{L"CH", static_cast<wchar_t>(Gumsmaq::cherries)},
	{L"PC", static_cast<wchar_t>(Gumsmaq::peach)},
	{L"MG", static_cast<wchar_t>(Gumsmaq::mango)},
	{L"pA", static_cast<wchar_t>(Gumsmaq::pineapple)},
	{L"cN", static_cast<wchar_t>(Gumsmaq::coconut)},
	{L"K", static_cast<wchar_t>(Gumsmaq::kiwi)},
	{L"T", static_cast<wchar_t>(Gumsmaq::tomato)},
	{L"eP", static_cast<wchar_t>(Gumsmaq::eggplant)},
	{L"AV", static_cast<wchar_t>(Gumsmaq::avocado)},
	{L"O", static_cast<wchar_t>(Gumsmaq::olive)},
	{L"BC", static_cast<wchar_t>(Gumsmaq::broccoli)},
	{L"LT", static_cast<wchar_t>(Gumsmaq::leafy_green)},
	{L"bPP", static_cast<wchar_t>(Gumsmaq::bell_pepper)},
	{L"CC", static_cast<wchar_t>(Gumsmaq::cucumber)},
	{L"hPP", static_cast<wchar_t>(Gumsmaq::hot_pepper)},
	{L"CN", static_cast<wchar_t>(Gumsmaq::corn)},
	{L"C", static_cast<wchar_t>(Gumsmaq::carrot)},
	{L"GA", static_cast<wchar_t>(Gumsmaq::garlic)},
	{L"0", static_cast<wchar_t>(Gumsmaq::onion)},
	{L"PT", static_cast<wchar_t>(Gumsmaq::potato)},
	{L"sPT", static_cast<wchar_t>(Gumsmaq::sweet_potato)},
	{L"cBR", static_cast<wchar_t>(Gumsmaq::croissant)},
	{L"bBR", static_cast<wchar_t>(Gumsmaq::bagel)},
	{L"BR", static_cast<wchar_t>(Gumsmaq::bread)},
	{L"fBR", static_cast<wchar_t>(Gumsmaq::french_bread)},
	{L"flBR", static_cast<wchar_t>(Gumsmaq::flatbread)},
	{L"pBR", static_cast<wchar_t>(Gumsmaq::pretzel)},
	{L"Q", static_cast<wchar_t>(Gumsmaq::cheese)},
	{L"EG", static_cast<wchar_t>(Gumsmaq::egg)},
	{L"?", static_cast<wchar_t>(Gumsmaq::cooking)},
	{L"BU", static_cast<wchar_t>(Gumsmaq::butter)},
	{L"pCK", static_cast<wchar_t>(Gumsmaq::pancakes)},
	{L"W", static_cast<wchar_t>(Gumsmaq::waffle)},
	{L"bM", static_cast<wchar_t>(Gumsmaq::bacon)},
	{L"cM", static_cast<wchar_t>(Gumsmaq::cut_of_meat)},
	{L"pM", static_cast<wchar_t>(Gumsmaq::poultry_leg)},
	{L"mM", static_cast<wchar_t>(Gumsmaq::meat_on_bone)},
	{L"HD", static_cast<wchar_t>(Gumsmaq::hotdog)},
	{L"hFF", static_cast<wchar_t>(Gumsmaq::hamburger)},
	{L"fFF", static_cast<wchar_t>(Gumsmaq::fries)},
	{L"pFF", static_cast<wchar_t>(Gumsmaq::pizza)},
	{L"sFF", static_cast<wchar_t>(Gumsmaq::sandwich)},
	{L"¿", static_cast<wchar_t>(Gumsmaq::stuffed_flatbread)},
	{L"FLF", static_cast<wchar_t>(Gumsmaq::falafel)},
	{L"TK", static_cast<wchar_t>(Gumsmaq::taco)},
	{L"BUR", static_cast<wchar_t>(Gumsmaq::burrito)},
	{L"TM", static_cast<wchar_t>(Gumsmaq::tamale)},
	{L"SL", static_cast<wchar_t>(Gumsmaq::salad)},
	{L"QQ", static_cast<wchar_t>(Gumsmaq::shallow_pan_of_food)},
	{L"FD", static_cast<wchar_t>(Gumsmaq::fondue)},
	{L"CF", static_cast<wchar_t>(Gumsmaq::canned_food)},
	{L"S", static_cast<wchar_t>(Gumsmaq::spaghetti)},
	{L"RA", static_cast<wchar_t>(Gumsmaq::ramen)},
	{L"SW", static_cast<wchar_t>(Gumsmaq::stew)},
	{L"CR", static_cast<wchar_t>(Gumsmaq::curry)},
	{L"suF", static_cast<wchar_t>(Gumsmaq::sushi)},
	{L"BN", static_cast<wchar_t>(Gumsmaq::bento)},
	{L"D", static_cast<wchar_t>(Gumsmaq::dumpling)},
	{L"Y", static_cast<wchar_t>(Gumsmaq::oyster)},
	{L"fsF", static_cast<wchar_t>(Gumsmaq::fried_shrimp)},
	{L"bR", static_cast<wchar_t>(Gumsmaq::rice_ball)},
	{L"R", static_cast<wchar_t>(Gumsmaq::rice)},
	{L"cR", static_cast<wchar_t>(Gumsmaq::rice_cracker)},
	{L"FCK", static_cast<wchar_t>(Gumsmaq::fish_cake)},
	{L"NICE", static_cast<wchar_t>(Gumsmaq::fortune_cookie)},
	{L"mCK", static_cast<wchar_t>(Gumsmaq::moon_cake)},
	{L"oSP", static_cast<wchar_t>(Gumsmaq::oden)},
	{L"dSP", static_cast<wchar_t>(Gumsmaq::dango)},
	{L"sSP", static_cast<wchar_t>(Gumsmaq::shaved_ice)},
	{L"I", static_cast<wchar_t>(Gumsmaq::ice_cream)},
	{L"icSP", static_cast<wchar_t>(Gumsmaq::icecream)},
	{L"pSP", static_cast<wchar_t>(Gumsmaq::pie)},
	{L"cCK", static_cast<wchar_t>(Gumsmaq::cupcake)},
	{L"CK", static_cast<wchar_t>(Gumsmaq::cake)},
	{L"bdCK", static_cast<wchar_t>(Gumsmaq::birthday)},
	{L"cuCK", static_cast<wchar_t>(Gumsmaq::custard)},
	{L"LL", static_cast<wchar_t>(Gumsmaq::lollipop)},
	{L"SP", static_cast<wchar_t>(Gumsmaq::candy)},
	{L"cbSP", static_cast<wchar_t>(Gumsmaq::chocolate_bar)},
	{L"pNHCL", static_cast<wchar_t>(Gumsmaq::popcorn)},
	{L"πR22πR", static_cast<wchar_t>(Gumsmaq::doughnut)},
	{L"BSC", static_cast<wchar_t>(Gumsmaq::cookie)},
	{L"chN", static_cast<wchar_t>(Gumsmaq::chestnut)},
	{L"pN", static_cast<wchar_t>(Gumsmaq::peanuts)},
	{L"CP", static_cast<wchar_t>(Gumsmaq::honey_pot)},
	{L"MLK", static_cast<wchar_t>(Gumsmaq::milk)},
	{L"bMLK", static_cast<wchar_t>(Gumsmaq::baby_bottle)},
	{L"HERESY", static_cast<wchar_t>(Gumsmaq::coffee)},
	{L"YAY/HARBOUR", static_cast<wchar_t>(Gumsmaq::tea)},
	{L"pYAY/pHARBOUR", static_cast<wchar_t>(Gumsmaq::teapot)},
	{L"mYAY/mHARBOUR", static_cast<wchar_t>(Gumsmaq::mate)},
	{L"bYAY/bHARBOUR", static_cast<wchar_t>(Gumsmaq::bubble_tea)},
	{L"?¿", static_cast<wchar_t>(Gumsmaq::beverage_box)},
	{L"¿?", static_cast<wchar_t>(Gumsmaq::cup_with_straw)},
	{L"sC2H5OH", static_cast<wchar_t>(Gumsmaq::sake)},
	{L"bC2H5OH", static_cast<wchar_t>(Gumsmaq::beer)},
	{L"bbC2H5OH", static_cast<wchar_t>(Gumsmaq::beers)},
	{L"cgC2H5OH", static_cast<wchar_t>(Gumsmaq::champagne_glass)},
	{L"wC2H5OH", static_cast<wchar_t>(Gumsmaq::wine_glass)},
	{L"tC2H5OH", static_cast<wchar_t>(Gumsmaq::tumbler_glass)},
	{L"ckC2H5OH", static_cast<wchar_t>(Gumsmaq::cocktail)},
	{L"trC2H5OH", static_cast<wchar_t>(Gumsmaq::tropical_drink)},
	{L"cC2H5OH", static_cast<wchar_t>(Gumsmaq::champagne)},
	{L"COLD", static_cast<wchar_t>(Gumsmaq::ice_cube)},
	{L"sNOT_FOOD", static_cast<wchar_t>(Gumsmaq::spoon)},
	{L"fkNOT_FOOD", static_cast<wchar_t>(Gumsmaq::fork_and_knife)},
	{L"fkpNOT_FOOD", static_cast<wchar_t>(Gumsmaq::fork_knife_plate)},
	{L"bsNOT_FOOD", static_cast<wchar_t>(Gumsmaq::bowl_with_spoon)},
	{L"tbNOT_FOOD", static_cast<wchar_t>(Gumsmaq::takeout_box)},
	{L"CHOP", static_cast<wchar_t>(Gumsmaq::chopsticks)},
	{L"NHCL", static_cast<wchar_t>(Gumsmaq::salt)},
};